//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITechnologyNET.FindUnusedFiles.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Directory {
            get {
                return ((string)(this["Directory"]));
            }
            set {
                this["Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>\.(gif|png|jpg|jpeg|bmp|ico|pdf|js|css|eot|svg|ttf|eot|otf|woff|woff2)$</string>
  <string>\.(gif|png|jpg|jpeg|bmp|ico)$</string>
  <string>\.(ttf|eot|otf|woff|woff2)$</string>
  <string>\.(js|css)$</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Find {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Find"]));
            }
            set {
                this["Find"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>\.(htm|html|aspx|ascx|master|cshtml|js|css|less)$</string>
  <string>\.(htm|html|php|js|css|less)$</string>
  <string>\.(js|css|less)$</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Search {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Search"]));
            }
            set {
                this["Search"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>\node_modules\</string>
  <string>\scripts\_reference.js</string>
  <string>gruntfile.js</string>
  <string>gulpfile.js</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Exclude {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Exclude"]));
            }
            set {
                this["Exclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExcludeChecked {
            get {
                return ((bool)(this["ExcludeChecked"]));
            }
            set {
                this["ExcludeChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ImagePreviewChecked {
            get {
                return ((bool)(this["ImagePreviewChecked"]));
            }
            set {
                this["ImagePreviewChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoUpdateCheck {
            get {
                return ((bool)(this["AutoUpdateCheck"]));
            }
            set {
                this["AutoUpdateCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7.00:00:00")]
        public global::System.TimeSpan AutoUpdateCheckFrequence {
            get {
                return ((global::System.TimeSpan)(this["AutoUpdateCheckFrequence"]));
            }
            set {
                this["AutoUpdateCheckFrequence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2015-01-01")]
        public global::System.DateTime UpdateLastCheck {
            get {
                return ((global::System.DateTime)(this["UpdateLastCheck"]));
            }
            set {
                this["UpdateLastCheck"] = value;
            }
        }
    }
}
